name: 'whatsapp'
version: '1.0.0'

profile: 'whatsapp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  whatsapp:
    +materialized: view 
    intermediate:
      +materialized: table
    core:
      +materialized: table
